#!/bin/bash
# Spec Init Project - プロジェクト仕様ディレクトリ構造を初期化
# Usage: init-project.sh
#
# 作成されるもの:
# - .claude/settings.json (Plan モード強制)
# - specs/ ディレクトリ構造
# - specs/templates/config.yaml (デフォルト設定)
# - specs/00_CONTEXT.md ~ 08_DEV_GUIDELINES.md

set -euo pipefail

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"

# 変数設定
DATE=$(date +%Y-%m-%d)

# カラー出力
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# ============================================================================
# 1. .claude/settings.json 作成（Plan モード強制）
# ============================================================================
setup_claude_settings() {
    info "Setting up .claude/settings.json (Plan mode enforcement)..."

    mkdir -p .claude

    if [[ -f ".claude/settings.json" ]]; then
        # 既存ファイルがある場合、defaultMode を確認
        if grep -q '"defaultMode"' .claude/settings.json 2>/dev/null; then
            warn "  .claude/settings.json already has defaultMode setting, skipping"
        else
            warn "  .claude/settings.json exists but no defaultMode, please add manually:"
            echo '    "permissions": { "defaultMode": "plan" }'
        fi
    else
        cat > .claude/settings.json << 'EOF'
{
  "permissions": {
    "defaultMode": "plan"
  }
}
EOF
        info "  Created .claude/settings.json with Plan mode enabled"
    fi
}

# ============================================================================
# 2. ディレクトリ作成
# ============================================================================
create_directories() {
    info "Creating directories..."
    mkdir -p specs/templates
    mkdir -p specs/features
    info "  Created specs/templates/"
    info "  Created specs/features/"
}

# ============================================================================
# 3. config.yaml 作成
# ============================================================================
create_config_yaml() {
    info "Creating specs/templates/config.yaml..."

    CONFIG_FILE="specs/templates/config.yaml"

    if [[ -f "$CONFIG_FILE" ]]; then
        warn "  $CONFIG_FILE already exists, skipping"
        return
    fi

    cat > "$CONFIG_FILE" << 'EOF'
# Spec Configuration
# Generated by /spec init-project
# Edit this file to configure your project settings

# テンプレートソース
# github: .github/ 内のテンプレートを使用
# builtin: ~/.claude/skills/spec/templates/ を使用
template_source: builtin

# テストコマンド（プロジェクトに合わせて編集してください）
test_commands:
  unit: ""
  integration: ""
  e2e: ""
  all: ""
  lint: ""
  dev: ""

# 工数スケール
effort_scale:
  - "小"
  - "中"
  - "大"
EOF

    info "  Created $CONFIG_FILE"
    warn "  Please edit test_commands in $CONFIG_FILE for your project"
}

# ============================================================================
# 4. テンプレート解決関数
# ============================================================================
resolve_project_template() {
    local name="$1"
    local project_template="specs/templates/project/${name}"
    local fallback_template="${SKILL_DIR}/templates/project/${name}"

    if [[ -f "$project_template" ]]; then
        echo "$project_template"
    elif [[ -f "$fallback_template" ]]; then
        echo "$fallback_template"
    else
        echo ""
    fi
}

# ============================================================================
# 5. プレースホルダ置換関数
# ============================================================================
replace_placeholders() {
    local content="$1"
    content="${content//\{\{DATE\}\}/$DATE}"
    echo "$content"
}

# ============================================================================
# 6. プロジェクト仕様ファイル作成
# ============================================================================
create_project_specs() {
    info "Creating project specification files..."

    local PROJECT_SPECS=(
        "00_CONTEXT.md"
        "01_DOMAIN.md"
        "02_SYSTEM_RULES.md"
        "03_USE_CASES.md"
        "04_API.md"
        "05_ARCHITECTURE.md"
        "06_TEST_STRATEGY.md"
        "07_OPERATIONS.md"
        "08_DEV_GUIDELINES.md"
    )

    for spec_file in "${PROJECT_SPECS[@]}"; do
        OUTPUT_FILE="specs/${spec_file}"

        # 既存ファイルがある場合はスキップ
        if [[ -f "$OUTPUT_FILE" ]]; then
            warn "  Skipping (exists): $OUTPUT_FILE"
            continue
        fi

        TEMPLATE=$(resolve_project_template "$spec_file")
        if [[ -n "$TEMPLATE" ]]; then
            info "  Creating from template: $OUTPUT_FILE"
            CONTENT=$(cat "$TEMPLATE")
            CONTENT=$(replace_placeholders "$CONTENT")
            echo "$CONTENT" > "$OUTPUT_FILE"
        else
            warn "  Template not found for $spec_file"
        fi
    done
}

# ============================================================================
# 7. .gitignore 更新
# ============================================================================
update_gitignore() {
    info "Checking .gitignore..."

    local GITIGNORE=".gitignore"
    local ENTRIES=(
        "# Spec temporary files"
    )

    if [[ ! -f "$GITIGNORE" ]]; then
        info "  Creating .gitignore"
        printf '%s\n' "${ENTRIES[@]}" > "$GITIGNORE"
    else
        local needs_update=false
        for entry in "${ENTRIES[@]}"; do
            if ! grep -qF "$entry" "$GITIGNORE" 2>/dev/null; then
                needs_update=true
                break
            fi
        done

        if $needs_update; then
            info "  Adding spec entries to .gitignore"
            echo "" >> "$GITIGNORE"
            printf '%s\n' "${ENTRIES[@]}" >> "$GITIGNORE"
        else
            info "  .gitignore already configured"
        fi
    fi
}

# ============================================================================
# Main
# ============================================================================
main() {
    echo ""
    echo "=========================================="
    echo " Spec-Driven Development - Project Init"
    echo "=========================================="
    echo ""

    setup_claude_settings
    create_directories
    create_config_yaml
    create_project_specs
    update_gitignore

    echo ""
    echo "=========================================="
    echo " Project initialized successfully!"
    echo "=========================================="
    echo ""
    echo "Structure:"
    echo "  .claude/"
    echo "  └── settings.json      (Plan mode enabled)"
    echo "  specs/"
    echo "  ├── 00_CONTEXT.md ... 08_DEV_GUIDELINES.md"
    echo "  ├── templates/"
    echo "  │   └── config.yaml    (Edit test commands!)"
    echo "  └── features/"
    echo ""
    echo "Next steps:"
    echo "  1. Edit specs/templates/config.yaml (set test commands)"
    echo "  2. Edit specs/00_CONTEXT.md (project context)"
    echo "  3. Start a new feature: /spec new {feature}"
    echo ""
}

main "$@"
